archive:
  format_overrides:
    - goos: windows
      format: zip
brew:
  github:
    owner: sjansen
    name: homebrew-mecha
  commit_author:
    name: sjansen
    email: sjansen@buscaluz.org
builds:
- env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  ldflags:
  - -s -w -X main.build={{.Version}}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '.*'
release:
  prerelease: true
