[[constraint]]
  name = "github.com/fatih/color"
  version = "v1.6.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "v4.3.1"

[[constraint]]
  name = "github.com/google/skylark"
  revision = "06804d924f8f4f36e25d858d0eb0bab8e1c8bc80"

[[constraint]]
  name = "github.com/rivo/tview"
  revision = "213c37c368f62e3a1a81f5c6dc3d2ce054d206af"
