[[constraint]]
  name = "github.com/fatih/color"
  version = "v1.7.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "v1.2.2"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "v4.5.0"

[[constraint]]
  name = "github.com/google/skylark"
  branch = "master"

[[constraint]]
  name = "github.com/rivo/tview"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[override]]
  name = "github.com/docker/docker"
  revision = "a422774e593b33bd287d9890544ad9e09b380d8c"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
