
[[constraint]]
  name = "github.com/fatih/color"
  version = "v1.6.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "v4.0.0-rc15"
